### ISSUE TITLE
Running from package.json with -o flag fails

### ISSUE THREAD

**Issue by Gijsjan** [indexzero/http-server#197]
I have this code to preview a production build:

    "scripts": {
        "server": "http-server -o build/production"
    }

Without the `-o` flag, `http-server` is started, but with the flag, I get an `Error: spawn EACCES`.

**Comment by indexzero** [comment]
Your user does not have the appropriate permissions to make `opener` work. I would open an issue there: https://github.com/domenic/opener

**Comment by nevir** [comment]
I don't think that's right.

The documentation for `-o` seems to indicate that it takes a URL path (`[path]`), but `http-server` is passing it to `opener` [as a _command_ to run](https://github.com/indexzero/http-server/blob/master/bin/http-server#L151), which is not what `opener` expects.

For example, in @Gijsjan's example, this is asking opener to use `build/production` as a command to launch the URL (instead of, say, spawning `open` on OS X)

**Comment by craigmichaelmartin** [comment]
Agree with @nevir. Some of outstanding PR's address this. If they could be merged, that would be great :)
