### ISSUE TITLE
Enhancement suggestion: Serve file with 'Content-Disposition', 'attachment' when request URL has ?download query

### ISSUE THREAD

**Issue by akaleeroy** [indexzero/http-server#201]
Something like

``` javascript
// If request URL has ?download query serve as download
if (req.query.hasOwnProperty("download")) {
  console.log('Just served this one as download!');
  res.setHeader('Content-Disposition', 'attachment');
}
```

This modification used to come in very handy to me when I wanted to get my smartphone to download stuff served from my PC.

Thanks!

**Comment by BigBlueHat** [comment]
@akaleeroy curious what you're doing instead?

It's not something we'd add to http-server directly (as defining URLs within the server would be a Bad Thing).

FWIW, if you're linking to these files, you can use the `download` attribute on an anchor tag: `<a download href="awesome.file">Download</a>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download

Somewhat related to this issue is the #360 issue which would cover situations where you *always* want a download triggered.
