### ISSUE TITLE
Show file transfer progress

### ISSUE THREAD

**Issue by roccomuso** [indexzero/http-server#211]
Is there a way to show the file transfer progress on the node.js console after having started the http-server?

**Comment by derhuerst** [comment]
Because of how a file transfer works, the server doesn't exactly know how much has been transferred. So it makes more sense to show this on the client side.

Also, `http-server` is based on [`ecstatic`](https://github.com/jfhbrook/node-ecstatic), so `ecstatic` has to support it. I don't think this should be part of a small & lightweight HTTP server.

**Comment by derhuerst** [comment]
On the client, things like `wget`, `curl`, a WebDAV client or a Browser might show you progress.
