### ISSUE TITLE
Daemon?

### ISSUE THREAD

**Issue by komocode** [indexzero/http-server#269]
Tried running it with forever, but doesn't work.

Tried putting httpserver.conf into /etc/init/ on Ubuntu 14.04

> start on filesystem and started networking
> respawn
> forever start `which http-server` -p 80 /home/(USERPATH)

But doesn't seem to run.

Maybe add a daemon option so I don't have to use forever?

**Comment by derhuerst** [comment]
> Tried running it with forever, but doesn't work.

What exactly did you try? `forever start -c http-server .` works just fine for me.

**Comment by komocode** [comment]
when you run it manually, seems to work just fine. But putting it in an upstart script, things just doesn't seem to work the way they want to. I'm trying to autostart the http-server when server boots up.

**Comment by derhuerst** [comment]
@komocode But IMO it's not the job of `http-server` to support daemonizing, since `forever` can do this and autostarting is a different problem.

**Comment by komocode** [comment]
It's a convenience feature. Much like how we have "-o Open browser window after starting the server". It's not the job of http-server to open a window after starting the server, but we have it anyways.

**Comment by derhuerst** [comment]
> It's a convenience feature. Much like how we have "-o Open browser window after starting the server". It's not the job of http-server to open a window after starting the server, but we have it anyways.

I also opposed the `-o` feature. :D

`forever` does a really nice job with daemonizing, especially since `http-server` is a command line app. `forever` has all the convenience features you may want. (;

Autostarting is really difficult to get it working cross-platform. Also, since you can launch `http-server` from the command line like any other tool, this should be perfectly possible with upstart.

**Comment by komocode** [comment]
Not saying autostart needs to be implemented, but making it run as a daemon makes it align itself to be a good alternative to other projects such as Apache

**Comment by derhuerst** [comment]
> Not saying autostart needs to be implemented, but making it run as a daemon makes http-server align itself to be a good alternative to other projects such as Apache

Then maybe create an npm module or a script that sets up `http-server` with autostarting and daemonizing. (:

I'm not sure `http-server` tries to be an alternative to Apache. And IMO it shouldn't. It is lightweight and doesn't require any setup. It doesn't have any cgi capabilities and no modules.

**Comment by komocode** [comment]
This conversation is getting side-tracked.

**Comment by derhuerst** [comment]
> `forever start which http-server -p 80 /home/(USERPATH)`

I didn't notice this before… Binding on ports `<1000` usually requires root privileges.

**Comment by komocode** [comment]
Correct, but the upstart script should be run as root already? Or is that incorrect?

**Comment by derhuerst** [comment]
Have you tried running `http-server -p 80` as root (without upstart)?

**Comment by komocode** [comment]
I have, requires sudo. I tried putting sudo in the script as well, but no effect.

**Comment by indexzero** [comment]
@komocode might run as `root`, might not. But, if it is running as `root` and you did

```
npm install -g http-server
```

*NOT* as `root` then you may have problems as well because that might not install in the same location depending on your setup. I would cache the result of `which http-server` and use the absolute path in your upstart script with `-p 8080`. If that works, then try `-p 80`.

**Comment by newmizanur** [comment]
Those trying using pm2 and global installation. Try this, `pm2 start /pathOfYourGlobalNodeModules/http-server/bin/http-server`
