### ISSUE TITLE
404 is "Not Found"

### ISSUE THREAD

**Issue by weirdoCHAO** [indexzero/http-server#315]

**Comment by derhuerst** [comment]
Which files are in the directory you ran `http-server` in? What URL did you type in your browser?

**Comment by JodyJSmith** [comment]
Bumping this because I am suddenly having the same issue. I can't load any of my includes from a relative path. I'm getting 404 errors in the console, but only when running in http-server, not off the file system.

e.g. `../bower_components/angular/angular.min.js` 
All my production dependencies are up one dir from my index.html (I don't want 3rd party code in my app directory).

The Chrome console is showing all include requests as being located in a child directory, but only when running in http-server: localhost:8080/bower_components/etc.

**Comment by derhuerst** [comment]
`http-server` doesn't allow and, by the HTTP specs, cannot deliver files outside the web root. You should either let `http-server` serve the directory above or symlink it into the web root using `ln -s`.

**Comment by JodyJSmith** [comment]
@derhuerst Thanks much, makes perfect sense.

**Comment by derhuerst** [comment]
Would you mind closing the issue to reduce cognitive load for the maintainer? Thanks!

**Comment by JodyJSmith** [comment]
closes #315

**Comment by derhuerst** [comment]
Didn't see that @weirdoCHAO opened the issue. @weirdoCHAO please close this.

**Comment by BigBlueHat** [comment]
House cleaning.

**Comment by SkutinAnton** [comment]
I use https://www.npmjs.com/package/live-server
