### ISSUE TITLE
How to add catch all redirect?

### ISSUE THREAD

**Issue by Altiano** [indexzero/http-server#338]
I need something like this

`app.get("*", callback)`

so every request url will be redirected to index.html. 
but since this package not using express, I don't know how to solve this.

**Comment by derhuerst** [comment]
See #30, #306, #271 and #123. They all seem to be bundled in #80.

**Comment by Altiano** [comment]
gonna read it then, thanks a lot :)

**Comment by Altiano** [comment]
I'm not sure, #80 doesn't provide any clear answer, 

I think all I need to do is just modifying some lines here: https://github.com/indexzero/http-server/blob/master/lib/http-server.js

But turns out, it probably more complex than that?

**Comment by derhuerst** [comment]
> I'm not sure, #80 doesn't provide any clear answer,

No, it is the proposal for this feature.

**Comment by houston3** [comment]
-P http://localhost:8080/? worked for me. Note the question mark at the end.

**Comment by thornjad** [comment]
The `-P http://localhost:8080?` method is rather brilliant, and I think that may be the answer here, since your `index.html` is essentially acting as the proxy for all other pages.

**Comment by BigBlueHat** [comment]
@thornjad let's get this added to the README.

Sending `200 OK` is an anti-HTTP pattern. While SPA's may "benefit" from it, it's bad architecture both generally and for deployed SPAs and should really only be used in development and not production. Even the Angular docs suggest it shouldn't be used permanently because it's bad for both UX and performance.

However, having it handy for development does help folks who are doing HTML and not HTTP, so solving it at the README layer sounds great. :smiley:

**Comment by vovarudomanenko** [comment]
if you are getting an error "zsh: no matches found", escape the question mark like shown in example below
```
npx http-server --proxy http://localhost:8080/\?
```
[more detailed explanation](https://www.reddit.com/r/zsh/comments/h9mdvc/why_do_i_get_this_error_zsh_no_matches_found/)
