### ISSUE TITLE
Default address to 127.0.0.1

### ISSUE THREAD

**Issue by kschluter** [indexzero/http-server#368]
Is there a reason the default address is 0.0.0.0 instead of 127.0.0.1? Defaulting it to the latter would save users from typing "-a 127.0.0.1" every time a server is started.

**Comment by yamboy1** [comment]
When I make a server the default address is `127.0.0.1:8080`. Could you post the output of running `http-server` (or just the part which contains the available addresses)

**Comment by yamboy1** [comment]
Sorry, just looked at the source code, turns out that on ubuntu the default address is `127.0.0.1:8080` but on other systems it is set to `0.0.0.0`
Why is this? @indexzero.

And also, how about a config file that overrides the defaults, that seems pretty handy.

Finally, @kschluter, if you are using `npm`, then you can set `npm start` to `http-server -a 127.0.0.1` and then you would just run `npm start` to start the server.

**Comment by kschluter** [comment]
@yamboy1 

> on ubuntu the default address is 127.0.0.1:8080 but on other systems it is set to 0.0.0.0
Why is this? @indexzero.

That's what I was wondering. Seems it should always be 127.0.0.1 (in source)

**Comment by BigBlueHat** [comment]
The default is set to `0.0.0.0`, so that `http-server` is ready to serve any incoming request from any IP address the machine might have. Setting it to the ["local loopback"](https://en.wikipedia.org/wiki/Localhost) `127.0.0.1` address would mean you'd only be able to request stuff via your local machine.

The code here https://github.com/indexzero/http-server/blob/7e9ff0b47164e360186480e5f98dceddeab23b63/bin/http-server#L123 is simply making sure that the link you get in the console output (or when using the `-o` option) will give your browser one it can actually use--since `0.0.0.0` isn't an actual IP, but just a request to listen for requests on any/all available IPs. This way, you get `http://127.0.0.1:8080/` in the console which you can copy/paste or click on to see the site your serving. You should also see your local network IP address just above that--which you could give to others on your network so they can test your server also. If you're setup with a public/Web-facing IP address, then you can also use that. Hence, `0.0.0.0` has value as the default. 😃 

Also `canonicalHost` in that code isn't a reference to Ubuntu's parent company. 😃 The experience should be the same on all platforms.
