### ISSUE TITLE
404 fallback to index.html

### ISSUE THREAD

**Issue by arthurkhlghatyan** [indexzero/http-server#385]
Hi there!
I need to fallback not found routes to my index.html file for react-router to work properly. I saw many related issues here but none of them are solved. Please pay attention to this feature because it's needed a lot.

Thanks.

**Comment by rdebeasi** [comment]
For reference, here's how Harp implements this feature: http://harpjs.com/docs/development/200-ok

**Comment by arthurkhlghatyan** [comment]
Thanks, @rdebeasi, right now I'm using serve package. It has an option called -s which is redirecting 404 routes to index.html automatically.

**Comment by BigBlueHat** [comment]
@arthurkhlghatyan as you've found many other packages already do this and some of them exist solely too offer this "fallback" system.

Generally sending the same HTML content and a 200 in response to any request made to your server breaks the Web (conceptually) and limits the browsers ability to help you via catching, prefetching, `304 Not Modified`, and other things that make for performance friendly sites.

Consequently, since its handled in other dedicated packages that are OK with that approach, I'd recommend anyone interested in that feature use those. This project is dedicated to being an HTTP server, so...always returning 200 isn't useful.

Cheers,
🎩
