### ISSUE TITLE
need to use file system modul

### ISSUE THREAD

**Issue by nekcv** [indexzero/http-server#425]
has a creating file function in index.html but get does not recognize require (fs)

**Comment by BigBlueHat** [comment]
http-server only serves *static* files--so there's no additional server-side processing and `require()` won't be run on the server.

Depending on how your `index.html` is setup you might be attempting to use require.js or similar from the client? If so, then there is a client-side bug that needs addressing...and (consequently) there's nothing to fix/change to http-server.

So. The bug is elsewhere. Sorry.
