### ISSUE TITLE
when I run http-server on mac, I receive ```zsh: command not found: http-server```

### ISSUE THREAD

**Issue by daGaiGuanYu** [indexzero/http-server#496]
I've just moved to macOS from win10. And I've never worked in a mac before. I've met many problems. This is one of them. I can't figure out what's wrong, because the error msg is too,,,,, simple. Can anyone can help me on this? Any help is appreciated. The env is followed. thanks.
+ macOS Mojave 10.14.1
![env](https://user-images.githubusercontent.com/27003009/52165812-7375c900-2740-11e9-975a-c50ca6acfc4d.png)

**Comment by thornjad** [comment]
The problem is that you've installed `http-server`  with `sudo`. `sudo` is a very powerful command, similar to administrator privileges. It would be useful to learn more about `sudo` and all it can do!

`http-server` usually should not be installed with `sudo`, so in this case you should do use `npm install -g http-server`, and then it should work!

I'm going to close this issue for now, but feel free to comment again if you have any trouble, questions or comments.

**Comment by daGaiGuanYu** [comment]
Sorry for forgetting this issue. Because I’ve been on my new year holiday. I’ve almost forgetten i’m a programmer. Thank you very much.

**Comment by thornjad** [comment]
Hey no problem! Hope you had a great holiday!

**Comment by GoodGuyGregory** [comment]
I'm still having this issue without Sudo. I have been using a Python alternative to this program and unfortunately alot of tuts etc use this module. Any assistance ?

**Comment by GoodGuyGregory** [comment]
Wait I fixed this issue using this [Stack Overflow](https://stackoverflow.com/questions/46851400/http-server-command-not-found) and the subsequent links on it took me to a Resolving an **EACCESS permissions error** which had some insightful tips that helped me complete a test module to a new global installation configuration for my NPM packages and also assisted with the `$PATH` insertion of http-server from that `~/.npm-global` directory the documentation guided me through. for future references feel free to check it out [EACESS PERMISSIONS DOCS](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally)

**Comment by IvanKatrenko** [comment]
npm install -g http-server     --- no function
