### ISSUE TITLE
Can I add a hot update?

### ISSUE THREAD

**Issue by rxliuli** [indexzero/http-server#505]
As the title, each time you need to refresh the URL, can't you automatically refresh the webpage in the browser?

**Comment by BigBlueHat** [comment]
That's a bit beyond scope for `http-server` (which isn't just for development). There are projects (usually connected to code bundlers like `webpack` or `browserify`) which watch files, (re)bundle them, and then reload your UX.

Since we don't do any file watching (and we're not likely too), then this one is beyond scope for us.

However, it *could* be done via a separate tool that could watch the same directory that `http-server` is serving out of and reload the related URL if/when the files on disk change. If you find such a tool, I'm more than happy to have it mentioned in the README.

Thanks for asking!

**Comment by rxliuli** [comment]
I have found the tools I need.

Front page page hot update

- [live-server](https://www.npmjs.com/search?q=live-server): http development server with built-in browser and hot update
- [anywhere](https://www.npmjs.com/package/anywhere): Similar to the live-server above (developed by the Chinese, it has not been updated in a year)

Nodejs hot update

- [nodemon](https://www.npmjs.com/package/nodemon): The nodejs program is automatically restarted after the file is modified.
- [supervisor](https://www.npmjs.com/package/supervisor): nodejs program run manager with hot update function (not updated in two years)

Finally, if I use webpack, I usually use webpack-dev-server. http-server is generally used to quickly start http service.
