### ISSUE TITLE
Question: Can I require(`http-server`) as a Node Module?

### ISSUE THREAD

**Issue by alistair-hmh** [indexzero/http-server#511]
I would like to use the `http-server` as a node module, so I can start the server dynamically based on user settings, eg:

```js
const httpServer = require('http-server');

const settings = require('./settings.js');

const server = httpServer.start({
	host: settings.host,
	port: settings.port
};

const stopServer = async () => {
	await server.stop();
	console.log('The server has stopped.');
};
```

Is something like this possible?

**Comment by thornjad** [comment]
Yes you can! However, since `http-server` is oriented towards CLI use, we don't currently have a friendly API like `.start` or `.stop`. There are also a couple things you won't get when using as a node module, such as logging.

You can check out the [CLI script](https://github.com/indexzero/http-server/blob/master/bin/http-server) to see how it uses `../lib/http-server` (which is what you get if you `require('http-server');`.

If you or anyone would like to open a PR with a friendlier module API without substantially increasing the size of the package, I'd love to see it!

I'm closing this issue for now, but feel free to keep commenting!
